### ISSUE TITLE
Getting Meal and Insulin Information from FreeStyle LibreLink APP

### ISSUE THREAD

**Issue by nilbasora** [FokkeZB/libreview-unofficial#3]
I hope this message finds you well. I am currently exploring the capabilities of the API, particularly in relation to its interaction with the FreeStyle LibreLink app. My understanding is that the API facilitates access to CGM data from FreeStyle LibreLink. However, I am also interested in determining if it is possible to retrieve other types of data, specifically meal and insulin records that users input into the app. I have not found any information about retrieving meal and insulin data. Thanks :)

**Comment by FokkeZB** [comment]
Hi @nilbasora,

This documentation indeed only covers the FreeStyle LibreLink API, which only deals with insulin data. Our son uses Loop to control his Omnipod, and Loop sends his data to Apple Health, NightScout and Tidepool.
